import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ABI from "../contract/contract.json";
import { useContractRead, useContractWrite, usePrepareContractWrite } from 'wagmi'
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  //const { ensData } = useEnsData(undefined);
  const [store, setStore] = useState(false);
  const [save, setSave] = useState(false);
  const { data: SwitchData, isError, isLoading } = useContractRead({
    address: '0xceb3A1a074952a81bf3Adf95cBedBD5fd1Ce7b64',
    abi: ABI,
    functionName: 'retrieve',
    onSuccess(data) {
      setStore(data)
    }
  })
  const { config: contractMintWriteConfig } = usePrepareContractWrite({
    address: '0xceb3A1a074952a81bf3Adf95cBedBD5fd1Ce7b64',
    abi: [
      {
        name: 'store',
        type: 'function',
        stateMutability: 'nonpayable',
        inputs: [{ internalType: 'bool', name: '_v', type: 'bool' }],
        outputs: [],
      },
    ],
    functionName: 'store',
    args: [store],
  });
  useEffect(() => {
    if (save) {
      storeWrite?.()
      setSave(false)
    }
  }, [store]);
  const {
    write: storeWrite,
    isLoading: isStoreLoading,
    isSuccess: isStoreStarted,
    error: StoreError,
  } = useContractWrite(contractMintWriteConfig);
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <div>
          <input type="radio" id="huey" name="drone" value="true"
            checked={store === true}
            onChange={(e) => {
              setStore(true)
              setSave(true)
            }}
          />
          <label>true</label>
        </div>

        <div>
          <input type="radio" id="dewey" name="drone" value="false"
            checked={store === false}
            onChange={(e) => {
              setStore(false)
              setSave(true)
            }}
          />
          <label>false</label>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
